apiVersion: v1
kind: Pod
metadata:
  name: app-vulnerable
  labels:
    app: node-vulnerable
spec:
  containers:
  - name: app
    image: demo-node-lfi:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: app-hardened
  labels:
    app: node-hardened
  annotations:
    # Questa annotazione dice al Kubelet di dire a Docker/containerd 
    # di applicare il profilo AppArmor "docker-node-hardened"
    container.apparmor.security.beta.kubernetes.io/app: localhost/docker-node-hardened
spec:
  containers:
  - name: app
    image: demo-node-lfi:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
